### ISSUE TITLE
Multiple lunchbox apps in same application

### ISSUE THREAD

**Issue by Korijn** [breakfast-studio/lunchboxjs#22]
Does lunchbox support multiple lunchbox app instances inside the same HTML application without using iframes?

**Comment by Korijn** [comment]
I guess all of these things should be scoped to either match the `app` lifetime or the `LunchboxWrapper` component lifetime. The latter makes more sense as it can be recreated over the app's lifetime.

One problem I see is that various functions (e.g. `setCustomRender`) will need to know what scope they apply to. I could simply parameterize with a key...? 🧠

**Comment by Korijn** [comment]
I'm inclined to scope everything to `app` since you can access it in anywhere in the context argument of setup functions. With the options API you can access the app via `this.$root`. That makes it accessible "everywhere".

Note that this approach is not the same as supporting multiple canvases and renderers etc _within a single lunchbox app_. That would be a next level of complication which is definitely out of scope here.

**Comment by SaFrMo** [comment]
Agreed on scoping to `app`, that definitely makes the most sense to me as well. I haven't looked into how useful it'd be but maybe `provide` and `inject` can help in this context, since they seem to perform a similar function to `this.$root`?

Also agreed on the multiple canvases/renderers question - that's something I started to think through with overrides [here](https://docs.lunchboxjs.com/dev/overrides/) but haven't gotten very far in. Basically, I think it'd make sense for Lunchbox to cover the most common use case of "one camera, scene, and renderer" out of the box, with some way to allow multiples of any of those if desired. (And alternates, like the CSS3DRenderer!) That'll be another issue for sure but it's good to keep in mind 😄

**Comment by SaFrMo** [comment]
@Korijn I went ahead and set up a quick demo of what I'm thinking in this branch, scoping the dpr variable to the app level rather than global. (Really appreciate you pulling together that list, that's going to come in very useful!)

Using `provide`, `inject`, and some utility functions can keep those variables more neatly scoped while still being easy enough to access and modify from an app - see the `useGlobals` utility in the `provide-and-inject` demo. 

(I also included a setter factory function per [these recommendations](https://vuejs.org/guide/components/provide-inject.html#working-with-reactivity) and exported keys separately per [these](https://vuejs.org/guide/components/provide-inject.html#working-with-symbol-keys) to handle injections using symbols. The utility functions are mainly to provide typings out of the box, which looks like it's working in the demo; they'll also allow for `useCamera`, `useScene`, etc backwards-compatibility for the couple of apps out there using Lunchbox :smile:)

Some globals, like the AutoRaycaster, are probably going to need to be converted to components and conditionally included in LunchboxWrapper - I think this'll be better in the long run since it keeps the focus on components rather than actual functions in the library. More on those as I get closer to work on them!

**Comment by SaFrMo** [comment]
Note that an up-to-date list of globals can be found in the readme on [this branch](https://github.com/breakfast-studio/lunchboxjs/tree/22-multiple-apps) - all going well so far!

**Comment by Korijn** [comment]
Sorry for the lack of communication - a little preoccupied with other projects - but the work you've done so far already looks good. I was struggling to perform the migration of globals myself since I'm not familiar enough with the "ensure" construct and minidom, so it's very cool to see you picking up on the task. It's pretty challenging!

I really love the idea of using provide and inject; it's the perfect way to inject dependencies to lower level code without being tightly coupled.

**Comment by SaFrMo** [comment]
No worries at all, thanks! I think I have a good "ensured -> provided" roadmap ready with the renderer as an example - I'll continue down that road and let you know when it's ready for a look. Definitely falling more into line with Vue standards like named slots, provide/inject, etc, so that's already very useful - thanks for asking about this!

**Comment by SaFrMo** [comment]
Getting closer on this - the last couple things to update should be interactions and the update source, otherwise this should be ready in the next week or two! This is actually trimming down the code by a huge amount and making things much more internally consistent, and I think I'll be able to remove the `ensure` concept entirely with the changes here. Very exciting stuff 😄

**Comment by SaFrMo** [comment]
@Korijn Got the basics for this up and running on the `22-multiple-apps` branch - you can check that out and try the Multiple Apps demo from `npm run dev` to see it in action! Roadmap from here is:

* Re-add interaction (should be the last thing needed to get back to full functionality)
* Update docs (no more `ensure` and much more futureproof default camera/scene/renderer setups now!)
* Release the new version

This'll take a few weeks, most likely, but I'll keep this thread updated!

**Comment by Korijn** [comment]
The build scrips in package.json don't work on my windows machine because it uses `rm -rf` and `cp`, and node.js forces cmd (instead of powershell), so it was quite trick to get `npm install` to work. But I got it to work and the demo runs:

![image](https://user-images.githubusercontent.com/1882046/185070475-1afd5c07-b18d-4bfd-9b25-7711e92adf2f.png)

Awesome!!

**Comment by SaFrMo** [comment]
Oh, thanks for catching that and apologies for the inconvenience! I've added those cross-platform issues as a note in #29 for the next release.

In the meantime, I've re-added interaction on the beta branch, so `npm i lunchboxjs@beta` should reenable hover/click events on existing projects. I'm closing this issue to continue documentation on #29, since multiple apps should be good to go in the beta!
