### ISSUE TITLE
Compatibility with nuxt3?

### ISSUE THREAD

**Issue by g0shed** [breakfast-studio/lunchboxjs#43]
hi there, is lunchbox compatible with nuxt3? and if so, how can it be installed?

**Comment by SaFrMo** [comment]
Hey! I haven't had a chance to try it out myself, but I believe LunchboxJS + Nuxt 3 should work together. I'd try seeing if Nuxt 3 supports multiple/custom renderers; if so, use the Nuxt 3 method for registering and using a custom renderer, and if not, try the following:

1. Add an element `<div id="lunchbox-container"></div>` in the template section of the component where you want your Lunchbox canvas mounted.
2. In the `script` section of that component, add:

```ts
// assuming ~/components is your projectRoot/components folder
// (I haven't used Nuxt since Nuxt 2, apologies if this is out of date!)
import LunchboxApp from '~/components/LunchboxApp.vue`
import { createApp } from 'lunchboxjs'

// then, on mount:
createApp(LunchboxApp).mount('#lunchbox-container')
```

3. Add a `LunchboxApp.vue` file in your `components` directory.
4. Write your normal LunchboxJS code in that component. For example, this should create a blue cube (note the `sizePolicy="container"` prop, which forces the canvas to constrain itself to the parent's dimensions instead of the full window - remove that prop if you want the canvas to take up the full window):

```html
<template>
    <lunchbox sizePolicy="container">
        <mesh position-z="-5">
            <boxGeometry/>
            <meshBasicMaterial color="blue"/>
        </mesh>
    </lunchbox>
</template>
```

This is the slightly messy route of mounting another Vue app inside your main Nuxt app, so note these caveats:

* `provide` and `inject` probably won't work, since these are two separate Vue apps without any knowledge of each other. You'll need to use other workarounds.
* You'll probably need to tear down the LunchboxJS app manually if you destroy its containing component. I'm not sure the best way to do this off the top of my head, so let me know if you'd like a hand figuring out and we can talk it through.

This kind of mixing renderers is a commonly-requested feature, so I'll create a new issue to add a simpler workflow for this. Thanks!

**Comment by g0shed** [comment]
I'll be trying on this week, sorry, been absent

**Comment by SaFrMo** [comment]
No worries at all! For anyone looking to solve this issue, I've added a [section to the docs](https://docs.lunchboxjs.com/installation/#nuxt-3) describing how to use Lunchbox with Nuxt. Marking this issue as complete, let me know if there are any problems with that approach!

**Comment by stlbucket** [comment]
@SaFrMo - your link above goes to a 404 - is there a new location?

**Comment by SaFrMo** [comment]
@stlbucket Yes, thanks for checking! The new version of Lunchbox is framework-independent (including working with Nuxt) and the installation instructions are [here](https://docs.lunchboxjs.com/install.html). Let me know if anything's not clear about working with Lunchbox 2 and Nuxt - Lunchbox 2 is just a set of HTML custom elements, so any instructions for using custom elements with Nuxt apply.
